###
# Large Rds file splitter and combinder
# Zane
# 2024-06-30
# Takes the large Rds files generated by brms and breaks them up into smaller
# files that can go in GH.
# Then, those small files can be combined into one large file that can be
# read in with readRDS().
###

detect_os <- function() {
	os_detected <- .Platform$OS.type
	
	if (os_detected == "windows") {
		crayon::green("Detected Windows OS.") |> rlang::inform()
	} else if (os_detected == "unix") {
		crayon::yellow("Detected a unix OS.") |> rlang::inform()
	} else {
		rlang::abort(paste0(
			"OS detected isn't 'windows' or 'unix'!\nThis code isn't configured",
			" to work with your OS. Sorry!"
		))
	}
	
	return(os_detected)
}

os_call <- function(os_detected, ...) {
	
	if (os_detected == "windows") {
		out <- shell(...)
	} else if (os_detected == "unix") {
		out <- system(...)
	} else {
		rlang::abort(paste0(
			"OS detected isn't 'windows' or 'unix'!\nThis code isn't configured",
			" to work with your OS. Sorry!"
		))
	}
	
	invisible(out)
}

model_split <- function() {
	mods <- c("mod-pt", "mod-sc", "mod-sp", "mod-ti")
	
	# Detect the OS and message user about it
	this_os <- detect_os()
	
	for (model in mods) {
		cur_loc <- here::here("results", "largefiles", "fits", paste0(model, ".Rds"))
		dst_dir <- here::here("results", "models-split", model)
		# Make sure a directory exists to save the splitted models
		dir.create(dst_dir, showWarnings = FALSE)
		
		# Create a string for the system command that uses the right file names
		split_cmd <-
			paste0(
				# Split command and options
				"split -b 25m ",
				# Current location of file
				"\"", cur_loc, "\" ",
				# Directory the splitted files will go to
				"\"", dst_dir, "/\""
			)
		
		# Invoke the bash system command
		res <- os_call(this_os, split_cmd)
	}
	
	invisible(res)
}

model_cat <- function() {
	mods <- c("mod-pt", "mod-sc", "mod-sp", "mod-ti")
	# Make sure the destination directory exists
	model_loc <- here::here("results", "largefiles", "mods")
	# Make sure a directory exists to save the splitted models
	dir.create(model_loc, showWarnings = FALSE, recursive = TRUE)
	
	# Detect the OS and message user about it
	this_os <- detect_os()
	
	for (model in mods) {
		split_dir <- here::here("results", "models-split", model)
		
		# Create a string for the system command
		cat_cmd <-
			paste0(
				# Split command and options
				"cat ",
				# Current location of file
				"\"", paste0(split_dir), "\"/* > ",
				# Directory the splitted files will go to
				"\"", here::here(model_loc, paste0(model, ".Rds")), "\""
			)
		
		# Invoke the bash system command
		res <- os_call(this_os, cat_cmd)
	}
	
	invisible(res)
}

# END OF FILE ####
